[workspace]
resolver = "2"
members = [
    "cargo-symex",
    "symex",
    "examples",
    "crates/llvm-ir",
    "crates/symex_lib",
    "crates/valid_derive",
    "armv6-m-examples"
]
exclude = ["symex-llvm-14-legacy"]

[profile.release]
debug = true
